# Default image (https://hub.docker.com/_/microsoft-dotnet-sdk)
image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test
#  - deploy

# Build Backend
build_backend:
  stage: build
  script:
    - 'dotnet build TowerDefence/TowerDefenceGame_LPB -c Release'
  artifacts:
    expire_in: 2 days
    paths:
      - 'TowerDefence/TowerDefenceGame_LPB/bin/net6.0/Release'
      - 'TowerDefence/TowerDefenceGame_LPB/obj/net6.0/Release'

#Build WPF View
build_view:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019
  tags: [windows]
  dependencies:
    - build_backend
  script:
    - 'dotnet build TowerDefence/TowerDefenceWPF -c Release'
  
# Build Test
# Will recompile Backend because it needs Debug build
build_test:
  stage: build
  dependencies:
  script:
    - 'dotnet build TowerDefence/TowerDefence_Test'
  artifacts:
    expire_in: 2 days
    paths:
      - 'TowerDefence/TowerDefenceGame_LPB/bin/net6.0/Debug'
      - 'TowerDefence/TowerDefenceGame_LPB/obj/net6.0/Debug'
      - 'TowerDefence/TowerDefence_Test/'

# Test
test_model:
  stage: test
  dependencies:
    - build_test
  script:
    - 'dotnet test TowerDefence/TowerDefence_Test'
  artifacts:
    expire_in: 1 week
    paths:
      - 'TowerDefence/TowerDefence_Test/TestResults'
