# Default image (https://hub.docker.com/_/microsoft-dotnet-sdk)
#image: mcr.microsoft.com/dotnet/sdk:6.0
image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019

stages:
  - build
  - test
#  - deploy

# Build
build_job:
  stage: build
  tags: [windows]
  script:
    - dotnet build TowerDefence/TowerDefence.sln

# Test
test_model:
  stage: test
  script:
    - dotnet test TowerDefence/TowerDefence_Test # We don't have this yet
